spring:
  application:
    name: europa

  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    #url: jdbc:mysql://localhost:3306/orion
    username: myuser
    password: secret
    #password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update